import { ChangeDetectorRef, Component, OnInit, AfterViewInit, ViewChild } from '@angular/core'; import { CommonModule } from '@angular/common'; import { Router } from '@angular/router'; import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card'; import { MatChipsModule } from '@angular/material/chips'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon'; import { MatInputModule } from '@angular/material/input'; import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator'; import { MatProgressBarModule } from '@angular/material/progress-bar'; import { MatSelectModule } from '@angular/material/select'; import { MatSort, MatSortModule } from '@angular/material/sort'; import { MatTableDataSource, MatTableModule } from '@angular/material/table'; import { ContractComplianceService } from '../../../services/contract-compliance.service'; import { VendorService, VendorRecord } from '../../../services/vendor.service';
@Component({selector:'app-certification-management',standalone:true,imports:[CommonModule,MatCardModule,MatButtonModule,MatIconModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatTableModule,MatPaginatorModule,MatChipsModule,MatSortModule,MatProgressBarModule],templateUrl:'./certification-management.html',styleUrl:'./certification-management.scss'})
export class CertificationManagement implements OnInit,AfterViewInit{
 constructor(private router:Router,private service:ContractComplianceService,private vendorService:VendorService,private cdr:ChangeDetectorRef){} totalCertifications=0;activeCertifications=0;expiringCertifications=0;expiredCertifications=0;displayedColumns=['certificationName','certificateNumber','vendorName','issuingAuthority','expiryDate','status','actions'];certifications:any[]=[];dataSource=new MatTableDataSource<any>();vendors:VendorRecord[]=[];@ViewChild(MatPaginator)paginator!:MatPaginator;@ViewChild(MatSort)sort!:MatSort;
 ngOnInit(){this.loadCertifications();this.vendorService.getVendors({page:1,size:1000}).subscribe({next:r=>{this.vendors=r.items||[];this.cdr.detectChanges();},error:e=>console.error(e)});} ngAfterViewInit(){this.dataSource.paginator=this.paginator;this.dataSource.sort=this.sort;}
 loadCertifications(){this.service.getCertifications().subscribe({next:rows=>{this.certifications=(rows||[]).map(c=>({id:c.id,vendorId:c.vendor_id,certificationName:c.certification_name,certificateNumber:c.certification_number,vendorName:c.vendor_name||`Vendor #${c.vendor_id}`,issuingAuthority:c.issuing_authority,issueDate:c.issue_date,expiryDate:c.expiry_date,status:this.status(c)}));this.updateStats();this.dataSource.data=[...this.certifications];this.cdr.detectChanges();},error:e=>{console.error(e);this.certifications=[];this.updateStats();this.dataSource.data=[];this.cdr.detectChanges();}});}
 private status(c:any){const d=this.days(c.expiry_date);return d<0?'Expired':d<=30?'Expiring Soon':c.status||'Valid';} private days(d:string){const t=new Date();t.setHours(0,0,0,0);return Math.ceil((new Date(d).getTime()-t.getTime())/86400000);} updateStats(){this.totalCertifications=this.certifications.length;this.activeCertifications=this.certifications.filter(c=>c.status==='Valid').length;this.expiringCertifications=this.certifications.filter(c=>c.status==='Expiring Soon').length;this.expiredCertifications=this.certifications.filter(c=>c.status==='Expired').length;}
 applyFilter(e:Event){this.dataSource.filter=((e.target as HTMLInputElement)?.value||'').trim().toLowerCase();} filterByStatus(s:string){this.dataSource.data=s?this.certifications.filter(c=>c.status===s):[...this.certifications];}
 addCertification(){const vendorId=Number(prompt('Vendor ID:',''));if(!vendorId)return;const name=prompt('Certification Name:','ISO 9001');if(!name)return;const number=prompt('Certificate Number:',`CERT-${Date.now()}`);if(!number)return;const authority=prompt('Issuing Authority:','');if(!authority)return;const issue=prompt('Issue Date (YYYY-MM-DD):',new Date().toISOString().split('T')[0]);const expiry=prompt('Expiry Date (YYYY-MM-DD):');if(!issue||!expiry)return;this.service.createCertification({vendor_id:vendorId,certification_name:name,certification_number:number,issuing_authority:authority,issue_date:issue,expiry_date:expiry}).subscribe({next:()=>{this.loadCertifications();alert('Certification created successfully.');},error:e=>alert(e?.error?.detail||'Unable to create certification.')});}
 viewCertificate(id:number){const c=this.certifications.find(x=>x.id===id);if(c)alert(`Certification\n${c.certificationName}\nCertificate: ${c.certificateNumber}\nVendor: ${c.vendorName}\nAuthority: ${c.issuingAuthority}\nExpiry: ${c.expiryDate}\nStatus: ${c.status}`);}
 editCertificate(id:number){const c=this.certifications.find(x=>x.id===id);if(!c)return;const name=prompt('Certification Name:',c.certificationName);const authority=prompt('Issuing Authority:',c.issuingAuthority);const expiry=prompt('Expiry Date (YYYY-MM-DD):',c.expiryDate);if(!name||!authority||!expiry)return;this.service.updateCertification(id,{certification_name:name,issuing_authority:authority,expiry_date:expiry}).subscribe({next:()=>{this.loadCertifications();alert('Certification updated successfully.');},error:e=>alert(e?.error?.detail||'Unable to update certification.')});}
 replaceCertificate(id:number){const c=this.certifications.find(x=>x.id===id);if(!c)return;const expiry=prompt('New Expiry Date (YYYY-MM-DD):',c.expiryDate);if(!expiry)return;this.service.updateCertification(id,{expiry_date:expiry,status:'Valid'}).subscribe({next:()=>{this.loadCertifications();alert('Certification renewed successfully.');},error:e=>alert(e?.error?.detail||'Unable to renew certification.')});}
}
