import { ChangeDetectorRef, Component, OnInit, AfterViewInit, ViewChild } from '@angular/core'; import { CommonModule } from '@angular/common'; import { Router } from '@angular/router'; import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card'; import { MatChipsModule } from '@angular/material/chips'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon'; import { MatInputModule } from '@angular/material/input'; import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator'; import { MatSelectModule } from '@angular/material/select'; import { MatSort, MatSortModule } from '@angular/material/sort'; import { MatTableDataSource, MatTableModule } from '@angular/material/table'; import { ContractComplianceService } from '../../../services/contract-compliance.service';
@Component({selector:'app-contract-renewal-dashboard',standalone:true,imports:[CommonModule,MatCardModule,MatButtonModule,MatIconModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatTableModule,MatPaginatorModule,MatChipsModule,MatSortModule],templateUrl:'./contract-renewal-dashboard.html',styleUrl:'./contract-renewal-dashboard.scss'})
export class ContractRenewalDashboard implements OnInit,AfterViewInit{
 constructor(private router:Router,private service:ContractComplianceService,private cdr:ChangeDetectorRef){} totalContracts=0;activeContracts=0;expiringContracts=0;expiredContracts=0;displayedColumns=['contractNumber','vendorName','expiryDate','remainingDays','status','actions'];contracts:any[]=[];dataSource=new MatTableDataSource<any>();@ViewChild(MatPaginator)paginator!:MatPaginator;@ViewChild(MatSort)sort!:MatSort;
 ngOnInit(){this.loadExpiringContracts();} ngAfterViewInit(){this.dataSource.paginator=this.paginator;this.dataSource.sort=this.sort;}
 loadExpiringContracts(){this.service.getContracts().subscribe({next:rows=>{this.contracts=(rows||[]).map(c=>{const days=this.days(c.end_date);return {id:c.id,contractNumber:c.contract_number,vendorName:c.vendor_name||`Vendor #${c.vendor_id}`,expiryDate:c.end_date,remainingDays:days,status:days<0?'Expired':days<=90?'Expiring Soon':(c.status||'Active')};}).filter(c=>c.remainingDays<=90);this.updateCounters();this.dataSource.data=[...this.contracts];this.cdr.detectChanges();},error:e=>{console.error(e);this.contracts=[];this.updateCounters();this.dataSource.data=[];this.cdr.detectChanges();}});}
 private days(d:string){const t=new Date();t.setHours(0,0,0,0);return Math.ceil((new Date(d).getTime()-t.getTime())/86400000);} updateCounters(){this.totalContracts=this.contracts.length;this.activeContracts=this.contracts.filter(c=>c.remainingDays>=0).length;this.expiringContracts=this.contracts.filter(c=>c.remainingDays>=0&&c.remainingDays<=90).length;this.expiredContracts=this.contracts.filter(c=>c.remainingDays<0).length;}
 applyFilter(e:Event){this.dataSource.filter=((e.target as HTMLInputElement)?.value||'').trim().toLowerCase();} filterByStatus(s:string){if(!s){this.dataSource.data=[...this.contracts];return;}this.dataSource.data=this.contracts.filter(c=>s==='expired'?c.remainingDays<0:c.remainingDays===Number(s));}
 refreshDashboard(){this.loadExpiringContracts();} renewContract(id:number){const target=this.contracts.find(c=>c.id===id);if(!target)return;const d=new Date(target.expiryDate);d.setFullYear(d.getFullYear()+1);this.service.renewContract(id,d.toISOString().split('T')[0]).subscribe({next:()=>{alert('Contract renewed successfully.');this.loadExpiringContracts();},error:e=>alert(e?.error?.detail||'Unable to renew contract.')});}
}
