import { ChangeDetectorRef, Component, OnInit, AfterViewInit, ViewChild } from '@angular/core'; import { CommonModule } from '@angular/common'; import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card'; import { MatChipsModule } from '@angular/material/chips'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon'; import { MatInputModule } from '@angular/material/input'; import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator'; import { MatProgressBarModule } from '@angular/material/progress-bar'; import { MatSelectModule } from '@angular/material/select'; import { MatSort, MatSortModule } from '@angular/material/sort'; import { MatTableDataSource, MatTableModule } from '@angular/material/table'; import { ContractComplianceService } from '../../../services/contract-compliance.service';
@Component({selector:'app-compliance-dashboard',standalone:true,imports:[CommonModule,MatCardModule,MatButtonModule,MatIconModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatTableModule,MatPaginatorModule,MatChipsModule,MatSortModule,MatProgressBarModule],templateUrl:'./compliance-dashboard.html',styleUrl:'./compliance-dashboard.scss'})
export class ComplianceDashboard implements OnInit,AfterViewInit{
 constructor(private service:ContractComplianceService,private cdr:ChangeDetectorRef){} totalVendors=0;compliantVendors=0;nonCompliantVendors=0;pendingVerification=0;expiredCompliance=0;compliancePercentage=0;displayedColumns=['vendorName','requirement','lastVerified','expiryDate','status','actions'];complianceRecords:any[]=[];dataSource=new MatTableDataSource<any>();@ViewChild(MatPaginator)paginator!:MatPaginator;@ViewChild(MatSort)sort!:MatSort;
 ngOnInit(){this.loadComplianceData();} ngAfterViewInit(){this.dataSource.paginator=this.paginator;this.dataSource.sort=this.sort;}
 loadComplianceData(){this.service.getComplianceOverview().subscribe({next:r=>{const rows=r.records||[];this.complianceRecords=rows.map((x:any)=>({id:x.vendor_id,vendorName:x.vendor_name,requirement:`Contract: ${x.contract_status} | Certification: ${x.certification_status} | Documents: ${x.document_status}`,lastVerified:'Current database status',expiryDate:'See contract/certification expiry',status:x.overall_status,percentage:x.compliance_percentage}));const s=r.summary||{};this.totalVendors=Number(s.total_vendors||0);this.compliantVendors=Number(s.compliant_vendors||0);this.nonCompliantVendors=Number(s.non_compliant_vendors||0);this.compliancePercentage=Number(s.average_compliance||0);this.pendingVerification=rows.filter((x:any)=>x.overall_status==='Pending').length;this.expiredCompliance=rows.filter((x:any)=>x.contract_status==='Non-Compliant'||x.certification_status==='Non-Compliant'||x.document_status==='Non-Compliant').length;this.dataSource.data=[...this.complianceRecords];this.cdr.detectChanges();},error:e=>{console.error(e);this.complianceRecords=[];this.totalVendors=this.compliantVendors=this.nonCompliantVendors=this.pendingVerification=this.expiredCompliance=this.compliancePercentage=0;this.dataSource.data=[];this.cdr.detectChanges();}});}
 applyFilter(e:Event){this.dataSource.filter=((e.target as HTMLInputElement)?.value||'').trim().toLowerCase();} filterByStatus(s:string){this.dataSource.data=s?[...this.complianceRecords.filter(x=>x.status===s)]:[...this.complianceRecords];}
 verifyCompliance(){this.loadComplianceData();}
 viewCompliance(id:number){const r=this.complianceRecords.find(x=>x.id===id);if(r)alert(`${r.vendorName}\n${r.requirement}\nOverall: ${r.status}\nScore: ${r.percentage}%`);}
 updateCompliance(id:number){const r=this.complianceRecords.find(x=>x.id===id);if(!r)return;alert('Compliance status is derived from contracts, certifications and vendor documents. Update the underlying record to change this result.');}
}
