import { AfterViewInit, Component, OnInit, ViewChild,
  ChangeDetectorRef} from '@angular/core';
import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { RouterModule } from '@angular/router';
import { MatCardModule } from '@angular/material/card'; import { MatTableModule, MatTableDataSource } from '@angular/material/table'; import { MatSort, MatSortModule } from '@angular/material/sort'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatInputModule } from '@angular/material/input'; import { MatSelectModule } from '@angular/material/select'; import { MatIconModule } from '@angular/material/icon'; import { MatButtonModule } from '@angular/material/button';
import { VendorReliabilityService } from '../../../services/vendor-reliability.service'; import { forkJoin, of } from 'rxjs'; import { catchError } from 'rxjs/operators';
@Component({selector:'app-performance-trend-analysis',standalone:true,imports:[CommonModule,FormsModule,RouterModule,MatCardModule,MatTableModule,MatSortModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatIconModule,MatButtonModule],templateUrl:'./performance-trend-analysis.html',styleUrl:'./performance-trend-analysis.scss'})
export class PerformanceTrendAnalysis implements OnInit,AfterViewInit{
 @ViewChild(MatSort) sort!:MatSort; constructor(private service:VendorReliabilityService, private cdr: ChangeDetectorRef){}
 averageReliability=0;improvingVendors=0;decliningVendors=0;stableVendors=0;searchText='';selectedCategory='';categories:string[]=[];displayedColumns=['vendor','category','monthly','yearly','trend','details'];trends:any[]=[];dataSource=new MatTableDataSource<any>([]);
 ngOnInit(){this.load()} ngAfterViewInit(){this.dataSource.sort=this.sort}
 load(){this.service.getRankings().subscribe({next:rows=>{const rankings=Array.isArray(rows)?rows:[];this.categories=[...new Set(rankings.map((r:any)=>r.vendor_category||'-'))];this.averageReliability=rankings.length?Math.round(rankings.reduce((s:number,r:any)=>s+Number(r.reliability_score??0),0)/rankings.length*100)/100:0;if(!rankings.length){this.setRows([]);return;}const requests=rankings.map((r:any)=>this.service.getHistory(r.vendor_id).pipe(catchError(()=>of([]))));forkJoin(requests).subscribe(histories=>{this.trends=rankings.map((r:any,i:number)=>{const history=Array.isArray(histories[i])?histories[i]:[];const latest=Number(history[0]?.reliability_score??r.reliability_score??0);const previous=Number(history[1]?.reliability_score??latest);const delta=latest-previous;return {vendor:r.vendor_name,category:r.vendor_category||'-',monthly:latest,yearly:Number(r.reliability_score??0),trend:delta>1?'Improving':delta<-1?'Declining':'Stable',id:r.vendor_id};});this.setRows(this.trends);});this.cdr.detectChanges();}, error:e=>console.error('Failed to load trend data:',e)})}
 setRows(rows:any[]){this.trends=rows;this.dataSource.data=rows;this.improvingVendors=rows.filter(r=>r.trend==='Improving').length;this.decliningVendors=rows.filter(r=>r.trend==='Declining').length;this.stableVendors=rows.filter(r=>r.trend==='Stable').length;this.applyFilters()}
 applyFilters(){const s=this.searchText.trim().toLowerCase();this.dataSource.filterPredicate=(d:any)=>(!s||d.vendor.toLowerCase().includes(s)||d.category.toLowerCase().includes(s))&&(!this.selectedCategory||d.category===this.selectedCategory);this.dataSource.filter=String(Date.now())}
}
