import { Component, OnInit,
  ChangeDetectorRef} from '@angular/core'; import { CommonModule } from '@angular/common'; import { Router } from '@angular/router'; import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatInputModule } from '@angular/material/input'; import { MatSelectModule } from '@angular/material/select'; import { MatButtonModule } from '@angular/material/button'; import { MatTableDataSource, MatTableModule } from '@angular/material/table'; import { MatIconModule } from '@angular/material/icon'; import { ProcurementService } from '../../../services/procurement.service';
@Component({selector:'app-communication-tracking',standalone:true,imports:[CommonModule,ReactiveFormsModule,MatCardModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatButtonModule,MatTableModule,MatIconModule],templateUrl:'./communication-tracking.html',styleUrl:'./communication-tracking.scss'})
export class CommunicationTracking implements OnInit{constructor(private fb:FormBuilder,private router:Router,private service:ProcurementService, private cdr: ChangeDetectorRef){} communicationForm!:FormGroup;purchaseOrders:any[]=[];selectedOrder:any=null;purchaseOrderNumber='-';vendorName='-';procurementStatus='-';communicationType='Vendor Communication';displayedColumns=['purchaseOrder','vendor','sentTime','responseTime','duration','status'];communicationHistory:any[]=[];dataSource=new MatTableDataSource<any>([]);
 ngOnInit(){this.communicationForm=this.fb.group({purchaseOrderId:['',Validators.required],messageSentTime:['',Validators.required],vendorResponseTime:['',Validators.required],responseDuration:[{value:'0 minutes',disabled:true}],communicationStatus:[{value:'Responded',disabled:true}],remarks:['']});this.communicationForm.get('purchaseOrderId')?.valueChanges.subscribe(id=>this.selectOrder(Number(id)));this.communicationForm.valueChanges.subscribe(v=>this.calculateDuration(v.messageSentTime,v.vendorResponseTime));this.loadOrders();this.loadHistory();}
 loadHistory(){this.service.getCommunicationRecords().subscribe({next:rows=>{this.communicationHistory=(rows||[]).map((r:any)=>({purchaseOrder:`PO #${r.purchase_order_id}`,vendor:`Vendor #${r.vendor_id}`,sentTime:new Date(r.message_sent_time).toLocaleString('en-GB'),responseTime:new Date(r.vendor_response_time).toLocaleString('en-GB'),duration:`${r.response_duration} minutes`,status:r.communication_status}));this.dataSource.data=this.communicationHistory;this.cdr.detectChanges();}, error:e=>console.error(e)})}
 loadOrders(){this.service.getPurchaseOrders({page:1,pageSize:100}).subscribe({next:o=>{this.purchaseOrders=(o||[]).filter(x=>String(x.status).toUpperCase()==='COMPLETED');if(this.purchaseOrders[0])this.communicationForm.patchValue({purchaseOrderId:this.purchaseOrders[0].id});this.cdr.detectChanges();}, error:e=>console.error(e)});}
 selectOrder(id:number){this.selectedOrder=this.purchaseOrders.find(o=>o.id===id)||null;if(!this.selectedOrder)return;this.purchaseOrderNumber=this.selectedOrder.po_number;this.procurementStatus=this.selectedOrder.status;this.service.getApprovedVendors().subscribe({next:vs=>this.vendorName=vs.find(v=>v.id===this.selectedOrder.vendor_id)?.company_name||`Vendor #${this.selectedOrder.vendor_id}`,error:()=>this.vendorName=`Vendor #${this.selectedOrder.vendor_id}`});}
 calculateDuration(a:any,b:any){if(!a||!b)return;const d=Math.round((new Date(b).getTime()-new Date(a).getTime())/60000);this.communicationForm.patchValue({responseDuration:`${Math.max(0,d)} minutes`},{emitEvent:false});}
 onSubmit(){if(this.communicationForm.invalid||!this.selectedOrder)return;const v=this.communicationForm.getRawValue();this.service.recordCommunication({purchase_order_id:Number(v.purchaseOrderId),message_sent_time:new Date(v.messageSentTime).toISOString(),vendor_response_time:new Date(v.vendorResponseTime).toISOString(),remarks:v.remarks||null}).subscribe({next:res=>{alert('Communication record saved successfully.');this.communicationHistory=[{purchaseOrder:this.purchaseOrderNumber,vendor:this.vendorName,sentTime:new Date(v.messageSentTime).toLocaleString('en-GB'),responseTime:new Date(v.vendorResponseTime).toLocaleString('en-GB'),duration:`${res?.response_duration??0} minutes`,status:res?.communication_status||'RESPONDED'},...this.communicationHistory];this.dataSource.data=this.communicationHistory;this.cdr.detectChanges();}, error:e=>alert(this.error(e,'Failed to save communication record.'))});}
 resetForm(){this.communicationForm.reset({purchaseOrderId:this.purchaseOrders[0]?.id||'',responseDuration:'0 minutes',communicationStatus:'Responded'});}applyFilter(e:Event){this.dataSource.filter=(e.target as HTMLInputElement).value.trim().toLowerCase();}goBack(){this.router.navigate(['/vendor-performance-dashboard']);}private error(e:any,f:string){const d=e?.error?.detail;return typeof d==='string'?d:Array.isArray(d)?d.map((x:any)=>x?.msg).filter(Boolean).join('\n')||f:d&&typeof d==='object'?JSON.stringify(d):f;}}
