import { Component, OnInit,
  ChangeDetectorRef} from '@angular/core'; import { CommonModule } from '@angular/common'; import { Router } from '@angular/router'; import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatCardModule } from '@angular/material/card'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatSelectModule } from '@angular/material/select'; import { MatInputModule } from '@angular/material/input'; import { MatButtonModule } from '@angular/material/button'; import { MatTableDataSource, MatTableModule } from '@angular/material/table'; import { MatIconModule } from '@angular/material/icon'; import { ProcurementService } from '../../../services/procurement.service';
@Component({selector:'app-service-rating',standalone:true,imports:[CommonModule,ReactiveFormsModule,MatCardModule,MatFormFieldModule,MatSelectModule,MatInputModule,MatButtonModule,MatTableModule,MatIconModule],templateUrl:'./service-rating.html',styleUrl:'./service-rating.scss'})
export class ServiceRating implements OnInit{constructor(private fb:FormBuilder,private router:Router,private service:ProcurementService, private cdr: ChangeDetectorRef){} serviceRatingForm!:FormGroup;purchaseOrders:any[]=[];selectedOrder:any=null;purchaseOrderNumber='-';vendorName='-';procurementStatus='-';completionDate='-';ratings=[5,4,3,2,1];displayedColumns=['purchaseOrder','vendor','overallRating','reviewedBy','date'];ratingHistory:any[]=[];dataSource=new MatTableDataSource<any>([]);
 ngOnInit(){this.serviceRatingForm=this.fb.group({purchaseOrderId:['',Validators.required],professionalism:['',Validators.required],customerSupport:['',Validators.required],documentationQuality:['',Validators.required],flexibility:['',Validators.required],communicationEffectiveness:['',Validators.required],issueResolution:['',Validators.required],overallServiceRating:['',Validators.required],comments:['']});this.serviceRatingForm.get('purchaseOrderId')?.valueChanges.subscribe(id=>this.selectOrder(Number(id)));this.loadOrders();this.loadHistory();}
 loadHistory(){this.service.getServiceRatings().subscribe({next:rows=>{this.ratingHistory=(rows||[]).map((r:any)=>({purchaseOrder:`PO #${r.purchase_order_id}`,vendor:`Vendor #${r.vendor_id}`,overallRating:r.overall_service_rating,reviewedBy:'Current User',date:new Date().toLocaleDateString('en-GB')}));this.dataSource.data=this.ratingHistory;this.cdr.detectChanges();}, error:e=>console.error(e)})}
 loadOrders(){this.service.getPurchaseOrders({page:1,pageSize:100}).subscribe({next:o=>{this.purchaseOrders=(o||[]).filter(x=>String(x.status).toUpperCase()==='COMPLETED');if(this.purchaseOrders[0])this.serviceRatingForm.patchValue({purchaseOrderId:this.purchaseOrders[0].id});this.cdr.detectChanges();}, error:e=>console.error(e)});}
 selectOrder(id:number){this.selectedOrder=this.purchaseOrders.find(o=>o.id===id)||null;if(!this.selectedOrder)return;this.purchaseOrderNumber=this.selectedOrder.po_number;this.procurementStatus=this.selectedOrder.status;this.completionDate=this.selectedOrder.updated_at?new Date(this.selectedOrder.updated_at).toLocaleDateString('en-GB'):'-';this.service.getApprovedVendors().subscribe({next:vs=>this.vendorName=vs.find(v=>v.id===this.selectedOrder.vendor_id)?.company_name||`Vendor #${this.selectedOrder.vendor_id}`,error:()=>this.vendorName=`Vendor #${this.selectedOrder.vendor_id}`});}
 onSubmit(){if(this.serviceRatingForm.invalid||!this.selectedOrder)return;const v=this.serviceRatingForm.value;this.service.recordServiceRating({purchase_order_id:Number(v.purchaseOrderId),professionalism:Number(v.professionalism),customer_support:Number(v.customerSupport),documentation_quality:Number(v.documentationQuality),flexibility:Number(v.flexibility),communication_effectiveness:Number(v.communicationEffectiveness),issue_resolution:Number(v.issueResolution),comments:v.comments||null}).subscribe({next:res=>{alert('Service rating saved successfully.');this.ratingHistory=[{purchaseOrder:this.purchaseOrderNumber,vendor:this.vendorName,overallRating:res?.overall_service_rating??'-',reviewedBy:'Current User',date:new Date().toLocaleDateString('en-GB')},...this.ratingHistory];this.dataSource.data=this.ratingHistory;this.cdr.detectChanges();}, error:e=>alert(this.error(e,'Failed to save service rating.'))});}
 resetForm(){this.serviceRatingForm.reset({purchaseOrderId:this.purchaseOrders[0]?.id||''});}applyFilter(e:Event){this.dataSource.filter=(e.target as HTMLInputElement).value.trim().toLowerCase();}goBack(){this.router.navigate(['/vendor-performance-dashboard']);}private error(e:any,f:string){const d=e?.error?.detail;return typeof d==='string'?d:Array.isArray(d)?d.map((x:any)=>x?.msg).filter(Boolean).join('\n')||f:d&&typeof d==='object'?JSON.stringify(d):f;}}
