import { ChangeDetectorRef, Component, OnInit, AfterViewInit, ViewChild } from '@angular/core'; import { CommonModule } from '@angular/common'; import { Router } from '@angular/router'; import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card'; import { MatChipsModule } from '@angular/material/chips'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon'; import { MatInputModule } from '@angular/material/input'; import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator'; import { MatSelectModule } from '@angular/material/select'; import { MatSort, MatSortModule } from '@angular/material/sort'; import { MatTableDataSource, MatTableModule } from '@angular/material/table'; import { ContractComplianceService } from '../../../services/contract-compliance.service';
@Component({selector:'app-contract-notifications',standalone:true,imports:[CommonModule,MatCardModule,MatButtonModule,MatIconModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatTableModule,MatPaginatorModule,MatChipsModule,MatSortModule],templateUrl:'./contract-notifications.html',styleUrl:'./contract-notifications.scss'})
export class ContractNotifications implements OnInit,AfterViewInit{
 constructor(private service:ContractComplianceService,private router:Router,private cdr:ChangeDetectorRef){} totalNotifications=0;expiringContracts=0;urgentNotifications=0;expiredContracts=0;displayedColumns=['contractNumber','vendorName','expiryDate','remainingDays','renewalStatus','notificationChannel','actions'];notifications:any[]=[];dataSource=new MatTableDataSource<any>();@ViewChild(MatPaginator)paginator!:MatPaginator;@ViewChild(MatSort)sort!:MatSort;
 ngOnInit(){this.loadNotifications();} ngAfterViewInit(){this.dataSource.paginator=this.paginator;this.dataSource.sort=this.sort;}
 loadNotifications(){this.service.getContractNotifications(90).subscribe({next:rows=>{this.notifications=(rows||[]).map(c=>{const d=this.days(c.end_date);return {id:c.id,contractNumber:c.contract_number||`CTR-${c.id}`,vendorName:c.vendor_name||`Vendor #${c.vendor_id}`,expiryDate:c.end_date,remainingDays:d,renewalStatus:d<0?'Expired':d<=7?'Urgent':d<=30?'30 Days Reminder':'90 Days Reminder',notificationChannel:'In-App'};});this.updateStats();this.dataSource.data=[...this.notifications];this.cdr.detectChanges();},error:e=>{console.error(e);this.notifications=[];this.updateStats();this.dataSource.data=[];this.cdr.detectChanges();}});}
 private days(d:string){const t=new Date();t.setHours(0,0,0,0);return Math.ceil((new Date(d).getTime()-t.getTime())/86400000);} updateStats(){this.totalNotifications=this.notifications.length;this.expiringContracts=this.notifications.filter(n=>n.remainingDays>=0&&n.remainingDays<=90).length;this.urgentNotifications=this.notifications.filter(n=>n.remainingDays>=0&&n.remainingDays<=7).length;this.expiredContracts=this.notifications.filter(n=>n.remainingDays<0).length;}
 applyFilter(e:Event){this.dataSource.filter=((e.target as HTMLInputElement)?.value||'').trim().toLowerCase();} filterByType(t:string){if(!t){this.dataSource.data=[...this.notifications];return;}this.dataSource.data=this.notifications.filter(n=>t==='expired'?n.remainingDays<0:n.remainingDays===Number(t));}
 viewNotification(id:number){this.router.navigate(['/contract-details',id]);}
 sendReminder(id:number){this.router.navigate(['/contract-details',id]);}
 markAsRead(id:number){alert('Contract expiry alerts are generated from current contract dates. Review the contract to acknowledge the alert.');this.viewNotification(id);}
}
