import { ChangeDetectorRef, Component, OnInit } from '@angular/core'; import { CommonModule } from '@angular/common'; import { ActivatedRoute, Router, RouterLink } from '@angular/router'; import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card'; import { MatChipsModule } from '@angular/material/chips'; import { MatIconModule } from '@angular/material/icon'; import { ContractComplianceService } from '../../../services/contract-compliance.service';
@Component({selector:'app-contract-details',standalone:true,imports:[CommonModule,RouterLink,MatCardModule,MatButtonModule,MatIconModule,MatChipsModule],templateUrl:'./contract-details.html',styleUrl:'./contract-details.scss'})
export class ContractDetails implements OnInit{
 contract:any={contractNumber:'-',contractTitle:'-',vendorName:'-',vendorId:'-',contractType:'-',procurementCategory:'-',startDate:'-',endDate:'-',contractValue:'-',paymentTerms:'-',sla:'-',warrantyDetails:'-',responsibleManager:'-',status:'-',remainingDays:'-',lastUpdated:'-',documentName:'No document uploaded',uploadDate:'-'};contractId=0;loading=true;
 constructor(private route:ActivatedRoute,private router:Router,private service:ContractComplianceService,private cdr:ChangeDetectorRef){}
 ngOnInit(){const id=Number(this.route.snapshot.paramMap.get('id'));if(!id){this.loading=false;return;}this.contractId=id;this.service.getContract(id).subscribe({next:c=>{this.contract={contractNumber:c.contract_number,contractTitle:c.contract_title,vendorName:c.vendor_name||`Vendor #${c.vendor_id}`,vendorId:c.vendor_id,contractType:c.contract_type,startDate:c.start_date,endDate:c.end_date,contractValue:`₹${Number(c.contract_value||0).toLocaleString('en-IN')}`,paymentTerms:this.parse(c.description ?? null,'Payment'),sla:this.parse(c.description ?? null,'SLA'),warrantyDetails:this.parse(c.description ?? null,'Warranty'),responsibleManager:this.parse(c.description ?? null,'Manager'),procurementCategory:this.parse(c.description ?? null,'Category'),status:this.status(c),remainingDays:`${this.days(c.end_date)} Days`,lastUpdated:c.updated_at?new Date(c.updated_at).toLocaleDateString('en-GB'):'-',documentName:c.document_path?c.document_path.split(/[\/]/).pop():'No document uploaded',uploadDate:c.created_at?new Date(c.created_at).toLocaleDateString('en-GB'):'-'};this.loading=false;this.cdr.detectChanges();},error:e=>{console.error(e);this.loading=false;this.cdr.detectChanges();}});}
 private days(d:string){const t=new Date();t.setHours(0,0,0,0);return Math.ceil((new Date(d).getTime()-t.getTime())/86400000);} private status(c:any){return this.days(c.end_date)<0?'Expired':c.status||'Active';} private parse(desc:string|null,key:string){const m=String(desc||'').split(' | ').find(x=>x.startsWith(key+':'));return m?m.slice(key.length+1).trim():'-';}
 editContract(){this.router.navigate(['/edit-contract',this.contractId]);}
 renewContract(){const current=new Date(this.contract.endDate);current.setFullYear(current.getFullYear()+1);const d=current.toISOString().split('T')[0];this.service.renewContract(this.contractId,d).subscribe({next:c=>{this.contract.endDate=c.end_date;this.contract.status=c.status;this.contract.remainingDays=`${this.days(c.end_date)} Days`;this.cdr.detectChanges();alert('Contract renewed successfully.');},error:e=>alert(e?.error?.detail||'Unable to renew contract.')});}
 previewDocument(){if(this.contract.documentName==='No document uploaded'){alert('No contract document has been uploaded.');return;}alert(`Contract document: ${this.contract.documentName}`);}
 downloadDocument(){if(this.contract.documentName==='No document uploaded'){alert('No contract document has been uploaded.');return;}this.service.downloadContractDocument(this.contractId).subscribe({next:b=>{const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=this.contract.documentName;a.click();URL.revokeObjectURL(u);},error:e=>alert(e?.error?.detail||'Unable to download document.')});}
}
