import { ChangeDetectorRef, Component, OnInit, AfterViewInit, ViewChild } from '@angular/core'; import { CommonModule } from '@angular/common'; import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card'; import { MatChipsModule } from '@angular/material/chips'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatIconModule } from '@angular/material/icon'; import { MatInputModule } from '@angular/material/input'; import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator'; import { MatSelectModule } from '@angular/material/select'; import { MatSort, MatSortModule } from '@angular/material/sort'; import { MatTableDataSource, MatTableModule } from '@angular/material/table'; import { ContractComplianceService } from '../../../services/contract-compliance.service';
@Component({selector:'app-vendor-documentation',standalone:true,imports:[CommonModule,MatCardModule,MatButtonModule,MatIconModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatTableModule,MatPaginatorModule,MatChipsModule,MatSortModule],templateUrl:'./vendor-documentation.html',styleUrl:'./vendor-documentation.scss'})
export class VendorDocumentation implements OnInit,AfterViewInit{
 constructor(private service:ContractComplianceService,private cdr:ChangeDetectorRef){} totalDocuments=0;activeDocuments=0;expiringDocuments=0;expiredDocuments=0;displayedColumns=['documentName','documentType','vendorName','uploadedDate','status','actions'];documents:any[]=[];documentTypes:string[]=[];dataSource=new MatTableDataSource<any>();@ViewChild(MatPaginator)paginator!:MatPaginator;@ViewChild(MatSort)sort!:MatSort;
 ngOnInit(){this.loadDocuments();} ngAfterViewInit(){this.dataSource.paginator=this.paginator;this.dataSource.sort=this.sort;}
 loadDocuments(){this.service.getVendorDocuments().subscribe({next:rows=>{this.documents=(rows||[]).map(d=>({id:d.id,vendorId:d.vendor_id,documentName:d.file_name,documentType:d.document_type,vendorName:d.vendor_name||`Vendor #${d.vendor_id}`,uploadedDate:d.uploaded_at,status:this.status(d),expiryDate:d.expiry_date}));this.documentTypes=[...new Set(this.documents.map(d=>d.documentType).filter(Boolean))];this.updateStats();this.dataSource.data=[...this.documents];this.cdr.detectChanges();},error:e=>{console.error(e);this.documents=[];this.updateStats();this.dataSource.data=[];this.cdr.detectChanges();}});}
 private status(d:any){if(d.expiry_date&&new Date(d.expiry_date)<new Date())return 'Expired';return d.status||'Valid';} updateStats(){this.totalDocuments=this.documents.length;this.activeDocuments=this.documents.filter(d=>d.status==='Valid').length;this.expiringDocuments=this.documents.filter(d=>d.expiryDate&&this.days(d.expiryDate)>=0&&this.days(d.expiryDate)<=30).length;this.expiredDocuments=this.documents.filter(d=>d.status==='Expired').length;}
 private days(d:string){const t=new Date();t.setHours(0,0,0,0);return Math.ceil((new Date(d).getTime()-t.getTime())/86400000);} applyFilter(e:Event){this.dataSource.filter=((e.target as HTMLInputElement)?.value||'').trim().toLowerCase();} filterByDocumentType(t:string){this.dataSource.data=t?this.documents.filter(d=>d.documentType.toLowerCase().includes(t.toLowerCase())):[...this.documents];} filterByStatus(s:string){this.dataSource.data=s?this.documents.filter(d=>d.status.toLowerCase().includes(s.toLowerCase())):[...this.documents];}
 uploadDocument(){const vendorId=Number(prompt('Vendor ID:',''));if(!vendorId)return;const type=prompt('Document Type:','Compliance Certificate');if(!type)return;const expiry=prompt('Expiry Date (YYYY-MM-DD, optional):','');const input=document.createElement('input');input.type='file';input.accept='.pdf,.doc,.docx,.jpg,.jpeg,.png';input.onchange=()=>{const file=input.files?.[0];if(!file)return;this.service.uploadVendorDocument(vendorId,type,file,expiry||undefined).subscribe({next:()=>{this.loadDocuments();alert('Document uploaded successfully.');},error:e=>alert(e?.error?.detail||'Unable to upload document.')});};input.click();}
 viewDocument(id:number){const d=this.documents.find(x=>x.id===id);if(d)alert(`Document\n${d.documentName}\nType: ${d.documentType}\nVendor: ${d.vendorName}\nStatus: ${d.status}`);}
 downloadDocument(id:number){const d=this.documents.find(x=>x.id===id);this.service.downloadVendorDocument(id).subscribe({next:b=>{const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=d?.documentName||'document';a.click();URL.revokeObjectURL(u);},error:e=>alert(e?.error?.detail||'Unable to download document.')});}
 replaceDocument(id:number){const d=this.documents.find(x=>x.id===id);if(!d)return;const type=prompt('Document Type:',d.documentType)||d.documentType;const input=document.createElement('input');input.type='file';input.accept='.pdf,.doc,.docx,.jpg,.jpeg,.png';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const expiry=prompt('Expiry Date (YYYY-MM-DD, optional):',d.expiryDate||'')||undefined;this.service.uploadVendorDocument(d.vendorId,type,f,expiry).subscribe({next:()=>{this.loadDocuments();alert('Replacement uploaded as a new document record.');},error:e=>alert(e?.error?.detail||'Unable to replace document.')});};input.click();}
 deleteDocument(id:number){if(!confirm('Delete this document?'))return;this.service.deleteVendorDocument(id).subscribe({next:()=>{this.loadDocuments();alert('Document deleted successfully.');},error:e=>alert(e?.error?.detail||'Unable to delete document.')});}
}
